export class Product {
  constructor(
    public _id: string,
    public product_id: string,
    public brand: string,
    public name: string,
    public series: string,
    public storage: string,
    public chipset: string,
    public ram: string,
    public sim: string,
    public wifi: string,
    public camera: string,
    public webcam: string,
    public screen_size: string,
    public screen_resolution: string,
    public price_range: string,
    public size_range: string,
    public battery: string,
    public display: string,
    public OS: string,
    public GPU: string,
    public GPS: string,
    public bluetooth: string,
    public dimension: string,
    public weight: string,
    public color: Array<string>,
    public security: string,
    public price: number,
    public sale: number,
    public status: boolean,
    public imageUrls: Array<string>,
    public interaction: {
      rating_point: number,
      rates: number,
      comments: number
    },
    public blog?: any, 
    public blog_raw?: any
  ) {}
}
