#### BUILD #####
build_frontend:
  stage: build
  variables:
    MODULE_NAME: frontend
    CI_IMAGE_NAME: $CI_REGISTRY_IMAGE/$MODULE_NAME:$CI_COMMIT_REF_SLUG
  script:
    - echo -n $CI_JOB_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    # - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -f $DOCKERFILE_PATH/$MODULE_NAME.Dockerfile -t $CI_IMAGE_NAME $SRC_PATH
    - docker push $CI_IMAGE_NAME
  tags:
    - minastik-runner-0
  only:
    refs:
      - develop

### DEPLOY #####
deploy_frontend:
  stage: deploy
  variables:
    MODULE_NAME: frontend
    CONTAINER_NAME: long.lc-datn_frontend
    CI_IMAGE_NAME: $CI_REGISTRY_IMAGE/$MODULE_NAME:$CI_COMMIT_REF_SLUG
  before_script:
    - echo DEPLOY frontend
  script:
    - ssh -o StrictHostKeyChecking=no -i $RUNNER_HOME_PATH/duybc.pem $SERVER_STG 
      "docker rm -f $CONTAINER_NAME; docker pull $CI_IMAGE_NAME; docker run -d --name $CONTAINER_NAME -p 3009:80 --restart unless-stopped $CI_IMAGE_NAME"
  tags:
    - minastik-runner-0
  only:
    refs:
      - develop